source 'https://github.com/CocoaPods/Specs.git'

target 'FranticApparatusObjC', :exclusive => true do
  pod "FranticApparatusObjC", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "FranticApparatusObjC", :path => "../"

  
end
